### PR TITLE
Remove Buildalyzer and use MSBuild more directly

### LINKED ISSUE #36: Windows support
The generator does not work on git-bash.

### PR DESCRIPTION
**Pull request by Saancreed**
Loading projects is now done using Roslyn's `MSBuildWorkspace` which in turn uses latest MSBuild available out of all .NET SDKs installed on the machine. To simplify metadata reference management, reference assemblies are now shipped with the generator itself (see `PreserveCompilationContext` [MSBuild property](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#preservecompilationcontext)). As an upside, handling of MSBuild projects is now a little more predictable.

In the process, we have also lost the ability to ensure that analyzed projects don't reference any unsupported package. I _think_ it should be possible to restore this check somehow, but I wasted quite a bit of time on that already and I'm not exactly willing to continue.

Some tests can no longer be run in parallel in the same process because MSBuild will _change the working directory of the entire process_ while processing projects/solutions. MSBuild itself can handle parallel builds because it actually uses multiple processes and not just multiple threads, but xunit doesn't know that. 

Fixes #36.

### CODE REVIEW

**Comment by marcin-dardzinski** [comment]
> Some tests can no longer be run in parallel in the same process because MSBuild will change the working directory of the entire process while processing projects/solutions.

Do you mean that restore creates obj folders or is it sth else? Maybe we can play with properties to generate a random obj path, but I guess having non parallel tests is not a big deal.

**Review by marcin-dardzinski — APPROVED** [review]

**Comment by Saancreed** [comment]
> > Some tests can no longer be run in parallel in the same process because MSBuild will change the working directory of the entire process while processing projects/solutions.
> 
> Do you mean that restore creates obj folders or is it sth else? Maybe we can play with properties to generate a random obj path, but I guess having non parallel tests is not a big deal.

It's because (afaik) MSBuild always `chdir`s to project's directory before executing any operation on said project for compatibility with some old MSBuild tasks. The end result would be failure to find `csproj` from some tests because another one is still running and relative paths we use as arguments in tests no longer work. 

Maybe we could instead resolve test assembly's location once and always pass absolute path by combining it with relative paths, but I'm afraid MSBuild won't like that.

**Comment by jakubfijalkowski** [comment]
Regarding the problem with tests - does that mean that the problem is only when searching for the `csproj` or also when running the `msbuild` during compilation? If the first, then we can just adjust project searching (e.g. gathering PWD in `static` ctor), if the latter - we can just make them sequential without any real loss for performance.

**Comment by Saancreed** [comment]
> Regarding the problem with tests - does that mean that the problem is only when searching for the `csproj` or also when running the `msbuild` during compilation? If the first, then we can just adjust project searching (e.g. gathering PWD in `static` ctor), if the latter - we can just make them sequential without any real loss for performance.

I did the latter just to be safe but there's a chance the former would work too. I suppose it's worth checking.

File: src/LeanCode.ContractsGenerator/ContractsCompiler.cs [hunk 1]
```diff
@@ -1,51 +1,59 @@
...
+            "System",
+            "System.Collections.Generic",
+            "System.IO",
+            "System.Linq",
+            "System.Net.Http",
+            "System.Threading",
+            "System.Threading.Tasks",
+        });
+
+        public static readonly ImmutableList<string> ReferenceAssemblyNames = ImmutableList.CreateRange(new[]
```
Comment (jakubfijalkowski) [inline src/LeanCode.ContractsGenerator/ContractsCompiler.cs:23]: Let's make it a set.

File: src/LeanCode.ContractsGenerator/ContractsCompiler.cs [hunk 2]
```diff
@@ -1,51 +1,59 @@
...
+        });
+
+        public static readonly ImmutableList<PortableExecutableReference> ReferenceAssemblies = DependencyContext.Default.CompileLibraries
+            .Where(cl => cl.Type == "referenceassembly")
+            .Where(cl => ReferenceAssemblyNames.Contains(cl.Name, StringComparer.InvariantCultureIgnoreCase))
+            .SelectMany(cl => cl.ResolveReferencePaths())
+            .Select(path => MetadataReference.CreateFromFile(path))
+            .ToImmutableList();
+
+        public static readonly ImmutableList<PortableExecutableReference> DefaultAssemblies = ReferenceAssemblies
```
Comment (jakubfijalkowski) [inline src/LeanCode.ContractsGenerator/ContractsCompiler.cs:46]: I would say - let's make the concatenation on `names` first, then resolve all the `MetadataReference`s in a single expression.

File: src/LeanCode.ContractsGenerator/ProjectLoader.cs [hunk 3]
```diff
@@ -1,75 +1,75 @@
...
+        private readonly MSBuildWorkspace msbuildWorkspace = MSBuildHelper.CreateWorkspace();
+        private readonly List<Project> projects = new();
 
         public ProjectLoader(CSharpCompilationOptions options)
         {
             this.options = options;
 
-            manager = new AnalyzerManager(null);
-            projects = new List<IProjectAnalyzer>();
+            msbuildWorkspace.WorkspaceFailed += static (sender, args) => Console.Error.WriteLine(args.Diagnostic.Message);
```
Comment (jakubfijalkowski) [inline src/LeanCode.ContractsGenerator/ProjectLoader.cs:18]: I'm... against this? Would rather prefer gathering the errors and then throwing, leaving error reporting to the parent method. That would improve separation of concerns.

File: src/LeanCode.ContractsGenerator/ProjectLoader.cs [hunk 4]
```diff
@@ -78,17 +78,18 @@ private static void VerifyProject(IProjectAnalyzer project)
...
             }
 
-            var proj = workspace.CurrentSolution.GetProject(id);
-            if (proj is not null)
+            var project = workspace.CurrentSolution.GetProject(id);
+
+            if (project is not null)
             {
-                var compilation = await proj
+                if (await project
```
Comment (jakubfijalkowski) [inline src/LeanCode.ContractsGenerator/ProjectLoader.cs:85]: Let's split this into variable + condition.

**Review by jakubfijalkowski — CHANGES_REQUESTED** [review]

File: src/LeanCode.ContractsGenerator/ProjectLoader.cs (hunk 3 above)
Comment (Saancreed) [reply src/LeanCode.ContractsGenerator/ProjectLoader.cs]: I'll just remove it for now.

File: src/LeanCode.ContractsGenerator/ContractsCompiler.cs (hunk 2 above)
Comment (Saancreed) [reply src/LeanCode.ContractsGenerator/ContractsCompiler.cs]: No concatenation of names, just checking two separate sets, but all references are now resolved at once.

**Review by jakubfijalkowski — APPROVED** [review]
